### ISSUE TITLE
Using the plotly.js binding without React?

### ISSUE THREAD

**Issue by mlaily** [Shmew/Feliz.Plotly#24]
Hi,

I'm new to Fable, and even more so to Feliz and React, so my question is probably stupid, but I'm very interested in the Fable binding for plotly.js you created, not so much in having to use React in my currently very simple project.

Is there any way to use Feliz.Plotly without React?

(As the next best thing, I would not mind too much if I have to use it to render a chart, but then can ignore it after that)

I tried something like the following, but I have to admit I have no idea what I'm doing, and it does not work :)
```fsharp
open Feliz
open Feliz.Plotly

let chart = 
    Plotly.plot [
        plot.traces [
            traces.scatter [
                scatter.x [ 1; 2; 3; 4 ]
                scatter.y [ 10; 15; 13; 17 ]
                scatter.mode.markers
            ]
            traces.scatter [
                scatter.x [ 2; 3; 4; 5 ]
                scatter.y [ 16; 5; 11; 9 ]
                scatter.mode.lines
            ]
            traces.scatter [
                scatter.x [ 1; 2; 3; 4 ]
                scatter.y [ 12; 9; 15; 12 ]
                scatter.mode [
                    scatter.mode.lines
                    scatter.mode.markers
                ]
            ]
        ]
    ]

ReactDOM.render(chart, document.getElementById "root")
```
(This fails at runtime with "Uncaught Error: Target container is not a DOM element.")

**Comment by Zaid-Ajaj** [comment]
Hi @mlaily, this error:
```
"Uncaught Error: Target container is not a DOM element."
```
Is coming from the call `document.getElementById "root"` and it happens because the HTML page didn't have an element with ID equal to "root" like this
```html
<div id="root"></div>
```
Can you please check your HTML page to see which element will end up being the container for the React app

**Comment by mlaily** [comment]
@Zaid-Ajaj Thanks for your answer.

I was too tired/lazy to check whether the root element was found or not yesterday, but you are right, it was null.

I did have a `<div id="root"></div>` in my html though, but it was declared after the `<script src="bundle.js"></script>` so it wasn't picked up.  I feel a bit dumb...

After fixing that, I did manage to render my chart :)

---

My question still stands though: Is it possible in some way to use parts of Feliz.Plotly without React?

**Comment by Shmew** [comment]
Hi @mlaily,

So this library wraps both `plotly.js` and `react-plotly.js`, it's possible to do this but not without an insignificant effort on my part, and it's not really in the scope of this project. This library in particular is not well suited for customization like this because I [generate](https://github.com/Shmew/Feliz.Plotly/blob/master/src/Feliz.Generator.Plotly/Program.fs) almost all of the files in the library.

Honestly I'd recommend just giving React a try, as it fits a FP paradigm quite well as opposed to the imperative nature of a framework-less site. If you really want to stay away from the React side of things, using [Fable.React](https://github.com/fable-compiler/fable-react) and [Elmish](https://elmish.github.io/elmish/) almost completely hides the fact that you're using a framework (this does have drawbacks though). @Zaid-Ajaj has quite a nice e-book/github site that you can follow along [here](https://zaid-ajaj.github.io/the-elmish-book/#/).

**Comment by mlaily** [comment]
> This library in particular is not well suited for customization because it [generates](https://github.com/Shmew/Feliz.Plotly/blob/master/src/Feliz.Generator.Plotly/Program.fs) almost all of the files in the library.
> That being said, the bulk of the code is usable plot.traces, plot.layout, and plot.config. You would need your own bindings [...]

That's nice, I didn't realize that. Thanks for the info!

> Honestly I'd recommend just giving React a try

I might, eventually, but it feels like this is overkill for what I'm doing... (And it's not free in terms of bundle size, maybe performance, and also in terms of the time I will have to spend learning all this :) )

Fable.React and Elmish are interesting, but as I understand it, it will only help with my last point.

Thanks for the links anyway, it might come handy when I'm ready.

And thanks for your work, and for taking the time to answer my question.
